### ISSUE TITLE
Sync lost with API

### ISSUE THREAD

**Issue by MH165emc** [kesteraernoudt/dobiss#135] opened 2023-03-26 13:01 UTC
## Version of the custom_component

Last version has been downloaded again today from GitHub and uploaded in HA custom integrations.

## Configuration

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
    language: "nl"
    tld: com


```

## Describe the bug

Lights and switches work fine, but after a while, synchronisation with the API is lost. Status of lights and switches is no longer up to date and no longer reacting to triggers (manually switching on/off). When reloading the integration, all is working fine again. 

## Debug log

```text

2023-03-26 14:10:49.148 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration dobiss which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
[home-assistant_dobiss_2023-03-26T12-56-45.483Z.log](https://github.com/kesteraernoudt/dobiss/files/11071643/home-assistant_dobiss_2023-03-26T12-56-45.483Z.log)

2023-03-26 14:11:14.646 WARNING (MainThread) [homeassistant.setup] Setup of hassio is taking over 10 seconds.
2023-03-26 14:11:16.753 WARNING (MainThread) [homeassistant.setup] Setup of ssdp is taking over 10 seconds.
2023-03-26 14:11:16.801 WARNING (MainThread) [homeassistant.setup] Setup of bluetooth is taking over 10 seconds.
2023-03-26 14:18:54.086 ERROR (MainThread) [frontend.js.latest.202303091] :0:0 Script error.


For your information: scripts.yaml is empty.

```

**Comment by MH165emc** [comment] 2023-03-26 13:11
<img width="1738" alt="Screenshot 2023-03-26 at 15 04 17" src="https://user-images.githubusercontent.com/128305301/227777753-b818e78e-13b8-4916-8e44-eab5e8e7f529.png">
These are the other active integrations

**Comment by MH165emc** [comment] 2023-03-26 13:16
In following screenshots, you can see that the status of "Kitchen Sink" is not synchronised. The status in Dobiss (DOBISS NXT 3.40 active) is always right.
<img width="277" alt="Screenshot 2023-03-26 at 15 13 01" src="https://user-images.githubusercontent.com/128305301/227778125-93fbedf9-e3aa-408c-b067-6c107a26594e.png">
<img width="542" alt="Screenshot 2023-03-26 at 15 13 11" src="https://user-images.githubusercontent.com/128305301/227778127-10d02bfb-53e8-44ab-8fef-5e6038e73b48.png">
<img width="543" alt="Screenshot 2023-03-26 at 15 13 29" src="https://user-images.githubusercontent.com/128305301/227778129-c998b841-efda-4210-b754-0f92e2c201ea.png">
<img width="834" alt="Screenshot 2023-03-26 at 15 13 53" src="https://user-images.githubusercontent.com/128305301/227778130-35e3a4d2-e5f2-477c-acbf-716eeffe4f9b.png">

**Comment by kesteraernoudt** [comment] 2023-03-27 07:07
Can you enable debugging for the integration as explained on the readme, and then provide me the log?

**Comment by MH165emc** [comment] 2023-03-28 18:10
> Can you enable debugging for the integration as explained on the readme, and then provide me the log?

[home-assistant_2023-03-28T17-49-51.885Z.log](https://github.com/kesteraernoudt/dobiss/files/11092895/home-assistant_2023-03-28T17-49-51.885Z.log)

**Comment by kesteraernoudt** [comment] 2023-03-28 21:41
Can you disable all debug logging except for dobiss debug? I've described how to do this in the readme of this project.

And can you than make sure the logging captures when the issue occurs? If you let me know the time it happens it's easier to analyze.

**Comment by MH165emc** [comment] 2023-04-01 11:22
Hi Arnoudt, Do you mean here: https://github.com/kesteraernoudt/dobiss/blob/dev/README.md? I already added the lines to my configuration.yaml file. 
<img width="502" alt="Screenshot 2023-04-01 at 13 16 53" src="https://user-images.githubusercontent.com/128305301/229285572-5f48dea0-1822-4e08-ae42-3765d650a821.png">
<img width="284" alt="Screenshot 2023-04-01 at 13 19 41" src="https://user-images.githubusercontent.com/128305301/229285725-d708fce2-b778-49d8-b97b-273ffc528bef.png">
I downloaded the log files via Settings/System/Logbook/Download full logbook. Can you clarify how to continue? Thanks for the support

**Comment by kesteraernoudt** [comment] 2023-04-01 11:44
Can you let me know at what time you saw the issue when this log was created?

**Comment by Ex0MaNiaC** [comment] 2023-05-14 21:10
Issue allready solved? I’m having the same problem

**Comment by kesteraernoudt** [comment] 2023-05-15 18:28
Unfortunately I haven't been able to pinpoint the exact issue. Would you mind enabling debug as well, install the latest dev version, and send me the logs? You can email them if you prefer...

**Comment by kesteraernoudt** [comment] 2023-06-04 08:34
I've created a new dev version which has an extra option to set a timeout for the dobiss connection:
![image](https://github.com/kesteraernoudt/dobiss/assets/1177997/006caaae-1ac0-4ce4-9cdb-7bd54bf1e82d)
Since I still can't reproduce this issue, this option should at least help by reconnecting if there hasn't been any communication with the dobiss NXT server for that number of seconds you configure it to be.
Can you let me know if this helps?

**Comment by Ex0MaNiaC** [comment] 2023-06-04 14:47
Thank you! Just installed the “dev” update. I will keep you updated.

**Comment by kesteraernoudt** [comment] 2023-06-10 12:40
Have you been able to test this?

**Comment by kesteraernoudt** [comment] 2023-08-03 21:55
closing this as the workaround should be ok.

**Closed by kesteraernoudt** 2023-08-03 21:55 UTC
